/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ClienteDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;

/**
 *
 * @author rafau
 */
public class JInternalFrameConsultarCliente extends javax.swing.JInternalFrame {

    private final Principal tela;
    private DefaultTableModel modelo;

    /**
     * Creates new form NewJInternalFrameConsultarCliente
     */
    public JInternalFrameConsultarCliente(Principal p) {
        super("Consultar Cliente", true, true, false, true);
        this.tela = p;
        initComponents();
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCOnsultarCliente = new javax.swing.JTable();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();

        setTitle("Consultar Cliente");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTableCOnsultarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "CPF", "RG", "Telefone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCOnsultarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableCOnsultarClienteMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCOnsultarCliente);
        if (jTableCOnsultarCliente.getColumnModel().getColumnCount() > 0) {
            jTableCOnsultarCliente.getColumnModel().getColumn(0).setResizable(false);
        }

        jButtonAlterar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonAlterar.setForeground(new java.awt.Color(0, 51, 153));
        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(204, 204, 255));
        jButtonExcluir.setForeground(new java.awt.Color(0, 51, 153));
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonPesquisar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonPesquisar.setForeground(new java.awt.Color(0, 51, 153));
        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pesquisar.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAlterar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        Cliente c = new Cliente();
        lerLinhaTabela(c);
        JInternalFrameEditarCliente jiec = new JInternalFrameEditarCliente(tela, c);
        tela.jdp.add(jiec);
        jiec.setVisible(true);
        jButtonPesquisar.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        limparTabela();

    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        ArrayList<Cliente> listC = new ArrayList();
        ClienteDAO cd = new ClienteDAO();
        listC = cd.readAll();
        preencheTabela(listC);
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        ClienteDAO cd = new ClienteDAO();
        int linha = this.jTableCOnsultarCliente.getSelectedRow();
        int id = Integer.parseInt(jTableCOnsultarCliente.getValueAt(linha, 0).toString());
        cd.removeByID(id);
        JOptionPane.showMessageDialog(rootPane, "Cliente excluído com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        limparTabela();
        jButtonPesquisar.setEnabled(true);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableCOnsultarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCOnsultarClienteMousePressed
        jButtonPesquisar.setEnabled(false);
    }//GEN-LAST:event_jTableCOnsultarClienteMousePressed
    private void limparTabela() {
        modelo = (DefaultTableModel) jTableCOnsultarCliente.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    private void lerLinhaTabela(Cliente c) {

        int linha = this.jTableCOnsultarCliente.getSelectedRow();
        c.setCodigo(Integer.parseInt(jTableCOnsultarCliente.getValueAt(linha, 0).toString()));
        c.setNome(jTableCOnsultarCliente.getValueAt(linha, 1).toString());
        c.setCpf(jTableCOnsultarCliente.getValueAt(linha, 2).toString());
        c.setRg(jTableCOnsultarCliente.getValueAt(linha, 3).toString());
        c.setTelefone(jTableCOnsultarCliente.getValueAt(linha, 4).toString());
        c.setEmail(jTableCOnsultarCliente.getValueAt(linha, 5).toString());
    }

    private void preencheTabela(ArrayList<Cliente> listC) {

        modelo = (DefaultTableModel) jTableCOnsultarCliente.getModel();

        String[] linha = {null, null, null, null, null, null};
        for (int i = 0; i < listC.size(); i++) {
            modelo.insertRow(i, linha);
            modelo.setValueAt(listC.get(i).getCodigo(), i, 0);
            modelo.setValueAt(listC.get(i).getNome(), i, 1);
            modelo.setValueAt(listC.get(i).getCpf(), i, 2);
            modelo.setValueAt(listC.get(i).getRg(), i, 3);
            modelo.setValueAt(listC.get(i).getTelefone(), i, 4);
            modelo.setValueAt(listC.get(i).getEmail(), i, 5);

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCOnsultarCliente;
    // End of variables declaration//GEN-END:variables
}
